### PR TITLE
Initial WebAPI Project Commit

### PR DESCRIPTION
**Pull request by townerr**
- Adding initial notifications WebAPI skeleton project.

@mattmarnien @JordanEGarcia @mendac017 @escalonn

### CODE REVIEW

**Review by mattmarnien — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Since this is just the skeleton code this looks good.

**Review by escalonn — APPROVED** [review]

**Review by escalonn — CHANGES_REQUESTED** [review]
`Fakebook-Notification.WebAPI` doesnt fit .net naming convention; there shouldn't be a hyphen and `API` should be `Api`. the fastest way to make the change is just delete and dotnet new again

**Comment by townerr** [comment]
- Changed the naming from `Fakebook-Notifications.WebAPI` to `FakebookNotifications.WebApi`
- Added the initial Testing project as `FakebookNotifications.Testing`
- Both projects target `net5.0`

**Review by escalonn — CHANGES_REQUESTED** [review]
i dont see a good reason for putting it down in a `Web API/` folder, at least not one with a space in it. have the `sln` file at most one folder down

it's safe to just move the whole sln folder out, or rename it, etc; the sln and csproj files contain only relative paths so there is nothing to break (but dont do it if the sln is open in VS, VS wont like it)

**Review by escalonn — APPROVED** [review]

**Pull request merged**
